version: "3.8"
services:
  server:
    container_name: ${BACKEND_CONTAINER_NAME}
    build: .
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BACKEND_PORT}:8080
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "TZ=Asia/Tokyo"

  db:
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "TZ=Asia/Tokyo"
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  mysql_data:
